// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuifpdorbbzgpcdqkqwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aWZwZG9yYmJ6Z3BjZHFrcXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzk0ODUsImV4cCI6MjA1OTk1NTQ4NX0.cGwxFOwrQL1miOGX5FdVqyDK9H-4DMgAduZyomkZ6uY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);